kind = "web"
previewPath = "/"
title = "Salão Ni Hair"
version = "1.0.0"
id = "artifacts/ni-hair"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 25276

[services.development]
run = "pnpm --filter @workspace/ni-hair run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/ni-hair", "run", "build" ]
publicDir = "artifacts/ni-hair/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "25276"
BASE_PATH = "/"
